---
# tasks for opensips installing OpenSIPS on RedHat

- name: Install prerequisites for RedHat
  yum:
    name: gpg
    state: present
  register: yum_prereq_result
  until: yum_prereq_result is success
  retries: 10
  delay: 2

- name: Setup repository key from keyserver
  rpm_key:
    key: "{{ opensips_rpm_key_url }}"
  register: yum_key_result
  until: yum_key_result is success
  retries: 10
  delay: 2

- name: Setup OpenSIPS repository (RedHat)
  yum:
    name: '{{ repo | replace(" ", "") }}'
    state: present
  vars:
    repo: >
      {{ opensips_yum_repo }}/{{ opensips_version }}/
      {{ opensips_build }}/el/{{ ansible_distribution_major_version }}/
      {{ ansible_architecture }}
      {% if opensips_yum_release is defined %}
      /opensips-yum-{{ opensips_build }}-
      {{ opensips_version }}-{{ opensips_yum_release }}.el
      {{ ansible_distribution_major_version }}.noarch.rpm
      {% else %}
      /repository.rpm
      {% endif %}
  register: yum_repo_install_result
  until: yum_repo_install_result is success
  retries: 10
  delay: 2

- name: Install OpenSIPS (RedHat)
  yum:
    name: opensips
    state: present
  notify:
    - opensips start
    - opensips restart
  register: yum_install_result
  until: yum_install_result is success
  retries: 10
  delay: 2

- name: Install OpenSIPS additional modules (RedHat)
  yum:
    name: '{{ opensips_modules }}'
    state: present
  when: opensips_modules is defined and opensips_modules | length
  notify:
    - opensips start
    - opensips restart
  register: yum_modules_install_result
  until: yum_modules_install_result is success
  retries: 10
  delay: 2
